const BillRouter = require('./Bill');
const KhachHangRouter = require('./KhachHang');
const XeRouter = require('./Xe');
const HieuXeRouter = require('./HieuXe');
const ChiTietDoanhSoRouter = require('./ChiTietDoanhSo');
const TaiKhoanRouter = require('./TaiKhoan');
const QuyDinhRouter = require('./QuyDinh');
const LoaiVatTuRouter = require('./LoaiVatTu');
const { isAdminAuth, isAuth } = require('../middlewares/AuthMiddleware');
const AccessoryRouter = require('./Accessory');
const WageRouter = require('./Wage');
const ParameterRouter = require('./Parameter');
const AccessoryImportFormRouter = require('./AccessoryImportForm');
const InventoryReportRouter = require('./InventoryReport');
const PhieuThuTien = require('./PhieuThuTien');
const DoanhSo = require('./DoanhSo');
const PhieuSuaChua = require('./PhieuSuaChua');
const PhieuTiepNhan = require('./PhieuTiepNhan');
const Home = require('./Home');

const route = (app) => {
  app.use('/api/bills',isAuth, BillRouter);
  app.use('/api/khachhangs',isAuth, KhachHangRouter);
  app.use('/api/xes',isAuth, XeRouter);
  app.use('/api/hieuxes',isAuth, HieuXeRouter);
  app.use('/api/chitietdoanhsos',isAuth, ChiTietDoanhSoRouter);
  app.use('/api/taikhoans', TaiKhoanRouter);
  app.use('/api/quydinhs', isAdminAuth, QuyDinhRouter);
  app.use('/api/loaivattus',isAuth, LoaiVatTuRouter);
  app.use('/api/wages',isAuth, WageRouter);
  app.use('/api/parameters',isAuth, ParameterRouter);
  app.use('/api/accessories',isAuth, AccessoryRouter);
  app.use('/api/accessory-import-forms',isAuth, AccessoryImportFormRouter);
  app.use('/api/inventory-reports',isAuth, InventoryReportRouter);
  app.use('/api/phieuthutiens',isAuth, PhieuThuTien);
  app.use('/api/doanhsos',isAuth, DoanhSo);
  app.use('/api/phieusuachua',isAuth,PhieuSuaChua);
  app.use('/api/phieutiepnhan',isAuth, PhieuTiepNhan);
  app.use('/api/home',isAuth, Home);
};

module.exports = route;
